cloudquery/cq-provider-aws

provider.go
We noticed that the `Account` array was always empty. This pr adds yaml tags to the config structs so it populates.
=> update plugin with yaml tags

go.mod, go.sum, provider/config.go, provider/provider.go, resources/eks/client.go, resources/eks/clusters.go
Adds support for ingesting EKS cluster information. I believe all fields should be captured.
There is no way to run a describe on multiple clusters at once, so I went with the approach to list clusters and describe one by one.
=> feat: eks support

provider/provider.go
fixes issue described in sdk docs where a global retry token bucket was being shared across all services https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/retries-timeouts/#customizing-behavior
This meant that if a single service hit a backoff, then every services subsequent requests would be heavily delayed, making ingestion slow.
=> fix: create new retryer configuration for each service

.gitignore, adding_a_new_resource.md, client/config.go, client/mocks/builders_test.go, client/mocks/mock_test.go, client/mocks/services.go, client/services.go, resources/directconnect_virtual_interfaces.go, resources/provider.go
I looked but it doesn't seem like this endpoint is paginated at all. There is no nextToken in the output: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/directconnect@v1.3.1#DescribeVirtualInterfacesOutput
and the [method call docs](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/directconnect@v1.3.1#Client.DescribeVirtualInterfaces) says it returns "all virtual interfaces for an AWS account"
=> feat: directconnect.virtual_interfaces

resources/integration_tests/integration_test.go
Skip integration tests if environment variable is not set. This helps to avoid running them by IDE/ editor each time you touch some files.
=> Run integration tests only when env var is set

adding_a_new_resource.md, client/mocks/mock_directconnect.go, client/services.go, docs/tables/aws_directconnect_lag_mac_sec_keys.md, docs/tables/aws_directconnect_lags.md, resources/directconnect_lags.go, resources/directconnect_lags_test.go, resources/provider.go
Lag schema: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/directconnect@v1.4.1/types#Lag
As we are already capturing DirectConnect Connections in a separate table, I opted to not resave that data, and instead just save the connectionIds in a StringArray.
Connection -> Lag is a Many:1 relationship, but not all connections necessarily have a Lag. Perhaps this is a scenario where we could introduce nullable FKs or something like that?
=> feat: directconnect lags

resources/s3_buckets.go
Should fix https://github.com/cloudquery/cloudquery/issues/157#issuecomment-893167568
=> Bugfix\ignore access denied in s3 relations

client/client.go
According to note here (https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specify-credentials-programmatically) all providers must be wrapped in credentials cache.
=> Use credentials cache

CHANGELOG.md, resources/cloudtrail_trails.go
cloudtrails tag list sometimes returned the error because region in cloudtrail ARN and in call options were different. Now cloudtrails are aggregated by region before doing get tags call.
fixes #236
=> Cloudtrail tags fix

client/client.go, client/errors.go, resources/organizations_accounts.go
The error might not be IAM policy related and needs to be treated
independent from the rest.
Fixes #254
=> Fix call to ListAccounts in a non-org user

client/client.go
=> extended logging of aws authorization error

CHANGELOG.md, client/client.go, docs/tables/aws_sagemaker_model_containers.md, go.mod, go.sum, resources/migrations/11_v0.8.4.down.sql, resources/migrations/11_v0.8.4.up.sql, resources/provider_test.go, resources/sagemaker_models.go
could add it in `cq-provider-sdk/provider/testing` instead maybe...
=> Ensure maximum table name length

resources/secretsmanager_secrets.go
Relates OR Closes #354 
```
...
```
=> fixed pk error - secretmanager

client/client.go
OptInStatus can be `not-opted-in` which means the region is disabled.
```
...
```
=> fix region filtering

resources/config_conformance_pack.go
This is a workaround untill this bug is fixed
https://github.com/aws/aws-sdk-go-v2/issues/1539
```
...
```
=> DescribeConformancePacks always returns AccessDeniedException in af-south-1

resources/organizations_accounts.go
I suggest ignoring this completely until AWS will come up with a better way to detect if we are in a root account or not, otherwise it makes the following two issues (I know this was the original suggestion of @spangenberg but I missed this PR or didn't understand completely how the diag works ):
1) the user experience on correct permissions is not smooth
2) our ci tests might fail because of that
```
...
```
=> ignore AccessDeniedException completely

resources/cognito_identity_pools.go, resources/cognito_user_pools.go, resources/mq_brokers.go
This is a temporary fix until regional availability feature is merged because right now our users have highly deteriorated user experiance.  
```
...
```
=> temporary fix until regional availability feature is merged

CHANGELOG.md, resources/provider/migrations/12_v0.8.5.down.sql, resources/provider/migrations/12_v0.8.5.up.sql, resources/services/elasticsearch/elasticsearch_domains.go
ElasticSearch domains [are unique](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/es/create-elasticsearch-domain.html) _per region_ but the PK was defined as `account_id, id`.
Manually tested in a "throwaway" AWS account.
=> Fix elasticsearch domains PK

client/client.go, client/client_test.go
```
cq-provider-aws % go test -tags=integration ./...                
?       github.com/cloudquery/cq-provider-aws   [no test files]
ok      github.com/cloudquery/cq-provider-aws/client    1.495s?       github.com/cloudquery/cq-provider-aws/client/mocks      [no test files]?       github.com/cloudquery/cq-provider-aws/docs      [no test files]?       github.com/cloudquery/cq-provider-aws/resources/forks   [no test files]?       github.com/cloudquery/cq-provider-aws/resources/forks/apigatewayv2      [no test files]?       github.com/cloudquery/cq-provider-aws/resources/provider        [no test files]ok      github.com/cloudquery/cq-provider-aws/resources/services/accessanalyzer …
```
=> fix: E2E tests

go.mod, resources/services/sagemaker/training_jobs.go
It was failing in [resolveSagemakerTrainingJobDebugHookConfigsCollectionConfigurations](https://github.com/cloudquery/cq-provider-aws/blob/c6d832b/resources/services/sagemaker/training_jobs.go#L640) but I went overboard with the nil checks.
=> fix: Sagemaker panics

client/errors.go, client/testing.go, go.mod, go.sum, resources/provider/provider.go, resources/services/redshift/mock_test.go, resources/services/wafv2/rule_groups_mock_test.go, resources/services/wafv2/web_acls_mock_test.go
I don't want to log/show pii-removed error messages to the end user (unless requested perhaps?) because that would be hard for debugging permissions and general setup. So maybe SDK `diag.Diagnostic` needs a new entry, a `redactedError`? Or just report multiple diag.Diagnostics, one normal and one redacted, and let the SDK choose which one to use when?
=> feat: Remove PII

docs/index.md
Lambda runtime automatically inserts credentials into the environment variables.
See Ben's comment at https://github.com/cloudquery/docs/pull/82#discussion_r797861081
```
```
=> docs: Remove 'labmda' from section about IAM auth

client/helpers.go, resources/services/efs/filesystems.go, resources/services/eks/clusters.go, resources/services/elbv1/load_balancers.go, resources/services/iam/group_policies.go, resources/services/iam/password_policies.go, resources/services/iam/role_policies.go, resources/services/iam/roles.go, resources/services/iam/user_policies.go, resources/services/lambda/functions.go, resources/services/lambda/layers.go, resources/services/s3/buckets.go
Most of the errors that should be ignored has a few common prefixes/suffixes. The function checks if error should be ignored and if it is it logs error as warning and allows to skip it. The function is used only in a few places. After PR approve I will propagate it to other resources.
closes #445
=> feat: Added generic api error ignore routine

resources/services/dynamodb/tables.go
- if dynamodb table is deleted during fetch the error is ignored now
=> fix: Dyanamodb table not found error ignored

docs/index.md
There were a few inaccuracies in the current docs:
- the AWS_PROFILE belongs in the 'shared config' section, not in the 'Environment variables' section.
- 'SDK is able to use SSO credentials stored in the ~/.aws directory' seems incorrect according to the docs I read.
```
```
=> docs: Copy authentication section from 'Getting Started' guide

client/errors.go
If the `err` is a `BaseError`, `NewBaseError(err, <TYPE>)` won't overwrite the type which results in errors having the wrong type.
=> fix: Diagnostic types in ErrorClassifier

docs/tables/aws_directconnect_gateways.md, go.mod, go.sum, resources/provider/migrations/postgres/20_v0.10.9.down.sql, resources/provider/migrations/postgres/20_v0.10.9.up.sql, resources/provider/migrations/timescale/20_v0.10.9.down.sql, resources/provider/migrations/timescale/20_v0.10.9.up.sql, resources/services/directconnect/gateways.go
A Direct Connect gateway is a globally available resource. You can create the Direct Connect gateway in any Region and access it from all other Regions. The following describe scenarios where you can use a Direct Connect gateway.[[^]](https://docs.aws.amazon.com/directconnect/latest/UserGuide/direct-connect-gateways-intro.html)
=> fix: DirectConnect Gateways are global

resources/provider/moduledata/drift/1/drift.hcl
Requires https://github.com/cloudquery/cloudquery/pull/515 for the deep mode to fully work.
=> fix: Drift: aws_cloudfront_distribution_origins should match aws_cloudfront_distribution.origin

resources/provider/moduledata/drift/1/drift.hcl
=> fix: Drift: Subresources should always match including the parent ID

resources/provider/moduledata/drift/1/drift.hcl
This is the smarter approach, as confirmed by a user in Discord.
Ref: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/imagebuilder/image.go#L103
=> fix: Drift: Match ec2.images with id/region

client/helpers.go, resources/services/s3/buckets.go
Especially around S3 API calls some properties return NotFound
when they are not set instead of empty result. This is completly
"normal" for these AWS APIs and no reason to log those messages.
=> fix: Remove unnecessary warn messages
