cloudquery/cq-provider-aws

- provider/provider.go
Adds retry to AWS provider https://github.com/cloudquery/cloudquery/issues/59
> BugFix: add retry to sdk

- go.mod
- provider/config.go
- provider/provider.go
Trying to help remediate https://github.com/cloudquery/cloudquery/issues/15
> BugFix: make retry configurable

- provider/provider.go
https://github.com/cloudquery/cloudquery/issues/58
> Add concurrent account fetching

- resources/ec2/instances.go
> fix: bulk insert ec2 for each describe call instead of one by one

- provider/provider.go
- resources/iam/users.go
Fixes #20.
Gets a list of users from ListUsers as well as a credential report and merges the data, ignoring any unused data from the credential report
> Fetch IAM User data from ListUsers and CredentialReport

- client/mocks/builders_test.go
- resources/s3_buckets.go
Closes https://github.com/cloudquery/cq-provider-aws/issues/29
> Add aws_s3_bucket_encryption_rules table

- resources/cloudwatch_alarms.go
Issue https://github.com/cloudquery/cq-provider-aws/issues/42
> Fix segmentation violation: Issue #42

- resources/iam_virtual_mfa_devices.go
https://github.com/cloudquery/cq-provider-aws/issues/44
> fix seg violation in iam_virtual_mfa_devices. Issue: #44

- client/config.go
- client/mocks/builders_test.go
- client/mocks/mock_test.go
- client/mocks/services.go
- client/services.go
- resources/ec2_transit_gateways.go
- resources/provider.go
The only aspect of transit gateway that this doesn't cover is TransitGatewayConnects and TransitGatewayConnectPeers. I'm not familiar with those resources and they seem to have references to a lot of various resources
> feat: transit gateway

- resources/iam_group_policies.go
- resources/iam_role_policies.go
- resources/iam_user_policies.go
> Fix no such entity in roles

- client/mocks/builders_test.go
- client/mocks/mock_test.go
- client/mocks/services.go
- client/services.go
- resources/ec2_vpn_gateways.go
- resources/provider.go
Adding support for Virtual Private Gateway resource in AWS.
> feat: Adding ec2.vpn_gateways

- .github/workflows/int_test.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Solves bug skipping darwin arm64
https://goreleaser.com/deprecations/#builds-for-darwinarm64
> Update github actions to go 1.16

- client/client.go
> Fix missing wafv2 client initialization

- client/client.go
- client/client_test.go
- resources/lambda_functions.go
- resources/route53_hosted_zones.go
> list aliases fix

- .github/workflows/int_test.yml
workflow to only be executed manually or on main push
> update integration workflow

- .github/workflows/lint.yml
- CHANGELOG.md
- go.mod
- go.sum
- resources/integration_tests/aws_ec2_images_test.go
- resources/integration_tests/infra/aws_ec2_images.tf
fixes cloudquery/cloudquery-issues#103
> Ec2.images integration test

- client/client.go
- client/helpers.go
- client/mocks/builders_test.go
- go.mod
- go.sum
- resources/ec2_byoip_cidrs.go
- resources/ec2_regional_config.go
- resources/ec2_regional_config_test.go
> fix byoip cidr errors

- resources/ec2_byoip_cidrs.go
> aws_ec2_byoip_cidrs added regions to ignore

- CHANGELOG.md
- resources/cloudtrail_trails.go
fixed previous PR. Added check to be sure that resource region is not nil
> Cloudtrail tags fix

- resources/cloudtrail_trails.go
> Fix: Cloudtrail Support

- resources/s3_buckets.go
> fixed logic ignoring error

- client/mocks/mock_emr.go
- client/services.go
- docs/tables/aws_emr_block_public_access_config_port_ranges.md
- docs/tables/aws_emr_block_public_access_configs.md
- resources/emr_block_public_access_configs.go
- resources/emr_block_public_access_configs_test.go
- resources/integration_tests/aws_emr_block_public_access_configs_test.go
- resources/integration_tests/aws_emr_clusters_test.go
- resources/provider.go
> Implement EMR Block Public Access resource

- CHANGELOG.md
- docs/tables/aws_ec2_security_groups.md
- resources/config_configuration_recorders.go
- resources/ec2_customer_gateways.go
- resources/ec2_ebs_volumes.go
- resources/ec2_security_groups.go
- resources/migrations/6_v0.6.1.down.sql
- resources/migrations/6_v0.6.1.up.sql
- resources/route53_delegation_sets.go
- resources/route53_health_checks.go
- resources/route53_hosted_zones.go
- resources/route53_traffic_policies.go
- resources/s3_buckets.go
> Add in Security Group ARN

- resources/organizations_accounts.go
> Fix e34d920: Call to ListAccounts in a non-org user (#337)

- client/helpers.go
Reverts cloudquery/cq-provider-aws#364
> Revert "Bugfix/ingore dns error"

- .github/workflows/endpoints.yml
> fixed endpoint workflow

- CHANGELOG.md
> close_v0.8.4

- client/testdata/initial_migration.hcl
> upgrade initial migration to v0.8.5 due to protocol upgrade v3

- client/client.go
- client/client_test.go
- client/config.go
- client/multiplexers.go
- client/testing.go
> Support Wildcard for Region

- .golangci.yml
> added asciicheck linter

- client/data/partition_service_region.json
> chore: regenerate partition_service_region.json

- CHANGELOG.md
> update CHANGELOG to v0.9.0

- .chglog/CHANGELOG.tpl.md
- .chglog/config.yml
- .github/workflows/pr_title.yml
- .github/workflows/release-notes.yml
> Add Changelog Automation

- resources/services/cloudtrail/trails.go
- resources/services/cloudtrail/trails_mock_test.go
> fix: Ignore organization tail tags if permissions are missing

- client/config.go
- client/data/partition_service_region.json
- client/testdata/assume_role.hcl
> fix: Continue remove account_id in config

- resources/services/cloudtrail/trails_mock_test.go
- resources/services/config/conformance_pack.go
fixes another bad region in config.packs that isn't supported and returns unknown error
> fix: Config packs bad region unknown error

- client/client.go
- client/config.go
- docs/index.md
> feat: Add role session name

- client/config.go
> fix: Fix init config

- .github/workflows/int_test.yml
> chore: Run integration tests on approved forks

- .github/workflows/lint_doc.yml
- .github/workflows/lint_golang.yml
- .github/workflows/test_integration.yml
- .github/workflows/test_unit.yml
> chore: Fix test_integration.yml

- .github/workflows/test_unit.yml
- client/data/partition_service_region.json
> feat: Update AWS regions

- .github/workflows/test_integration.yml
> chore: Fix is_organization_member job

- .github/workflows/test_integration.yml
> chore: Final fix to test_integration.yml

- resources/provider/migrations/postgres/16_v0.10.2.down.sql
- resources/provider/migrations/postgres/16_v0.10.2.up.sql
- resources/provider/migrations/timescale/16_v0.10.2.down.sql
- resources/provider/migrations/timescale/16_v0.10.2.up.sql
- resources/services/rds/certificates.go
- fixed pk constraint for aws_rds_certificates
closes #449
> fix: Fixed pk constraint in aws_rds_certificates

- .github/workflows/depndabot.yml
> chore: Add depndabot cq-provider-sdk

- client/client.go
- client/client_test.go
- client/config.go
- client/mocks/mock_organizations.go
- client/organizations.go
- client/organizations_test.go
- client/services.go
- docs/index.md
- go.sum
- resources/services/organizations/accounts.go
> feat: AWS Org Support

- client/organizations.go
- go.mod
- go.sum
> fix: Empty admin account edge case

- .github/workflows/depndabot.yml
> chore: Removed duplicated dependabot

- docs/index.md
It was removed in PR #474 - my bad...
> docs: Re-Add bullet about aws-sso.

- resources/provider/migrations/timescale/18_v0.10.7.up.sql
- resources/provider/migrations/timescale/19_v0.10.8.down.sql
- resources/provider/migrations/timescale/19_v0.10.8.up.sql
> fix: TSDB migration for aws_route53_traffic_policy_versions

- client/errors.go
- go.mod
- go.sum
Since summary messages now include the appended error message, we override the embedded error using `WithError` to make it look pretty.
> chore: Update SDK

- client/errors.go
Proper redaction affects how the errors are grouped.
> fix: Classify ratelimit errors as throttling, redaction fixes

- .github/workflows/lint_doc.yml
- .github/workflows/lint_golang.yml
- .github/workflows/terraform_apply.yml
- .github/workflows/terraform_plan.yml
- .github/workflows/test_unit.yml
- scripts/terraform-apply-all.sh
- scripts/terraform-apply-changes-only.sh
- scripts/terraform-fmt-change-only.sh
- scripts/terraform-init-change-only.sh
- scripts/terraform-plan-change-only.sh
- scripts/terraform-validate-all.sh
- scripts/terraform-validate-change-only.sh
> chore: Sync form .github

- resources/services/route53/hosted_zones.go
> fix: Route53 hosted zones ListResourceRecordSets pagination

- client/client.go
- resources/provider/moduledata/drift/1/drift.hcl
> fix: Drift: CF stacks

- .github/workflows/test_integration.yml
Update is-organization-member to 167d83f7b2972fbed7920155f9eadc6debada5de
> chore: Debug is-organization-member (verbose)
